name: tommy
description: A Flutter client for the Genny Project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_appauth: ^2.4.1
  jaguar_jwt: ^3.0.0
  http: ^0.13.4
  protobuf: ^2.0.1
  flutter_dotenv: ^5.0.2
  grpc: ^3.0.2
  minio: ^3.5.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  geoff:
    # path: /home/joseph/development/geoff
    git: 
      url: https://github.com/Kibibibit/geoff
      ref: c5e7a8f3ebfc74bb3f273e48340c1c422867398a
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  assets:
    - .env
  uses-material-design: true
