name: tommy
description: A Flutter client for the Genny Project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_appauth: ^2.4.1
  jaguar_jwt: ^3.0.0
  http: ^0.13.4
  protobuf: ^2.0.1
  flutter_dotenv: ^5.0.2
  grpc: ^3.0.2
  minio: ^3.5.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  geoff:
    git: 
      url: https://github.com/Kibibibit/geoff
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  assets:
    - .env
  uses-material-design: true