name: "Slacker"
description: "Lazy, no-frills Slackbot GitHub Action that does the bare minimum."
inputs:
  SLACK_URL:
    description: "Slackbot webhook URL"
    required: true
  SLACK_MSG:
    description: "Message in plaintext"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":" ${{ inputs.SLACK_MSG }} "}' ${{ inputs.SLACK_URL }}
      shell: bash
