# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    Dir.chdir("../..") do
      sh('sh', 'build.sh', options[:file], "_", "ios")
    end
    echo(message:Dir["../../**/*.ipa"].first())
    upload_to_testflight(ipa: File.expand_path(Dir["../../**/*.ipa"].first()))
  end

  lane :screenshots do
    capture_screenshots(workspace: "Runner.xcworkspace", scheme: "FastlaneScreenshots")
    frame_screenshots(white: true)
    upload_to_app_store
  end
end

