name: android-beta

on:
  push:
    branches:
      - "*-android-beta"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.4"
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android
        run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: android-build-files
          path: ./build/app/outputs/flutter-apk/app-release.apk
  deploy-android:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Download Android build file
        uses: actions/download-artifact@v2
        with:
          name: android-build-files
      - uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: beta
          file: app-release.apk
