name: android-beta

on:
  push:
    branches:
      - "*-beta"
  workflow_dispatch:

env:
  flutter_version: "1.20.2"
  java_version: "12.x"

jobs:
  build-android:
    runs-on: self-hosted
    steps:
      - uses: ./.github/slacker
        with:
          SLACK_URL: ${{ secrets.SLACK_URL }}
          SLACK_MSG: "Starting Android beta build"
      - uses: ./.github/seditor
        with:
          INPUT_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FILE_PATH: "./android/app/google-services.json"
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android
        run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: android-build-files
          path: ./build/app/outputs/flutter-apk/app-release.apk
      - uses: ./.github/slacker
        with:
          SLACK_URL: ${{ secrets.SLACK_URL }}
          SLACK_MSG: "Android beta build completed"
  deploy-android:
    needs: build-android
    runs-on: self-hosted
    steps:
      - name: Download Android build file
        uses: actions/download-artifact@v2
        with:
          name: android-build-files
      - uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: alpha
          file: app-release.apk
      - uses: ./.github/slacker
        with:
          SLACK_URL: ${{ secrets.SLACK_URL }}
          SLACK_MSG: "Android beta build deployed to beta testers"
