name: android-final

on:
  push:
    branches:
      - "*.0"
  workflow_dispatch:

jobs:
  android-final:
    runs-on: self-hosted
    steps:
      - name: Echo
        run: echo "Final stable Android app"
