name: Flutter build Android
on: push

env:
  flutter_version: "1.20.2"
  java_version: "12.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android
        run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: Android build files
          path: |
            /Users/runner/work/tommy/tommy/build/app/outputs/flutter-apk/app-release.apk
