name: build-deploy-ios
on:
  push:
    branches:
      - master

env:
  flutter_version: "1.20.2"
  java_version: "12.x"

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: ios-build-files
          path: /Users/runner/work/tommy/tommy/build/ios/iphoneos/Runner.app
      - uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: /Users/runner/work/tommy/tommy/build/ios/iphoneos/Runner.app
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@v1.0.7
        with:
          args: '{\"channel\":\"CT6CF0UJW\",\"text\":\"iOS build deployed to testers\"}'
