name: ios-beta

on:
  push:
    branches:
      - "*-beta"
  workflow_dispatch:

env:
  flutter_version: "1.20.2"
  java_version: "12.x"

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: ios-build-files
          path: /Users/runner/work/tommy/tommy/build/ios/iphoneos/Runner.app
  deploy-ios:
    needs: build-ios
    runs-on: self-hosted
    steps:
      - name: Download iOS build file
        uses: actions/download-artifact@v2
        with:
          name: ios-build-files
      - uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: Runner.app
