name: ios-beta

on:
  push:
    branches:
      - "*-beta"
  workflow_dispatch:

env:
  flutter_version: "1.22.4"

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: build
        run: ./deploy-all.sh
