name: secret-test

on: push

jobs:
  secret-test:
    runs-on: self-hosted
    env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    steps:
      - uses: actions/checkout@v2
      - name: Inject secret into json
        run: |
          ./injectJSON.sh $GOOGLE_SERVICES_JSON
          cat ./android/app/google-services.json
          echo "Build app now"
