name: slack

on:
  workflow_dispatch:
    inputs:
      slack:
        description: "Enter a Slack message"
        required: true

jobs:
  slack:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/slacker
        with:
          SLACK_URL: ${{ secrets.SLACK_URL_TEST }}
          SLACK_MSG: ${{ github.event.inputs.slack }}
